; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Auto-Maskin PCB Assembly Helper"
#define MyAppVerName "PCB Assembly Helper P1A"
#define MyAppPublisher "Auto-Maskin AS"
#define MyAppURL "http://www.auto-maskin.com/"
#define MyAppExeName "PCBAsemblyHelper.exe"
#define QTDIR "C:\Qt\5.1.1\mingw48_32"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

AppId={{ED6E522C-9383-4CAD-A5AA-20A167380989}
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\Auto-Maskin\PCBAssemblyHelper
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=PCBAsemblyHelper
Compression=lzma
SolidCompression=yes

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: ..\..\build-PCBAsemblyHelper-Desktop_Qt_5_1_1_MinGW_32bit-Release\release\PCBAsemblyHelper.exe; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\Qt5Core.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\Qt5Gui.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\Qt5Widgets.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\Qt5Svg.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\libgcc_s_dw2-1.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\icuin51.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\icuuc51.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\icudt51.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\libstdc++-6.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\bin\libwinpthread-1.dll; DestDir: {app}; Flags: ignoreversion
Source: {#QTDIR}\plugins\platforms\qwindows.dll; DestDir: {app}\platforms; Flags: ignoreversion

[Icons]
Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName};
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}
Name: {commondesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: quicklaunchicon

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#MyAppName}}; Flags: nowait postinstall skipifsilent
